package com.mongodb.mongopush.model;

import java.util.Arrays;
import java.util.List;

public enum MongoPushTestSequence {

	POC_DRIVER_MONGO_PUSH_DATA_SYNC(Arrays.asList(
			MongoPushTestEvent.EXECUTE_POC_DRIVER,
			MongoPushTestEvent.INITIAL_DATA_INSERTED,
			MongoPushTestEvent.SHUTDOWN_POC_DRIVER,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_DATA,
			MongoPushTestEvent.INITIAL_SYNC_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH
			)),
	
	POC_DRIVER_MONGO_PUSH_DATA_ONLY_SYNC(Arrays.asList(
			MongoPushTestEvent.EXECUTE_POC_DRIVER,
			MongoPushTestEvent.INITIAL_DATA_INSERTED,
			MongoPushTestEvent.SHUTDOWN_POC_DRIVER,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_DATA_ONLY,
			MongoPushTestEvent.INITIAL_SYNC_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH
			)),
	
	POC_DRIVER_MONGO_PUSH_DATA_ONLY_SYNC_VERIFY(Arrays.asList(
			MongoPushTestEvent.EXECUTE_POC_DRIVER,
			MongoPushTestEvent.INITIAL_DATA_INSERTED,
			MongoPushTestEvent.SHUTDOWN_POC_DRIVER,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_DATA_ONLY,
			MongoPushTestEvent.INITIAL_SYNC_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_VERIFY,
			MongoPushTestEvent.VERIFICATION_TASK_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH
			)),
	
	POC_DRIVER_MONGO_PUSH_DATA_SYNC_VERIFY(Arrays.asList(
			MongoPushTestEvent.EXECUTE_POC_DRIVER,
			MongoPushTestEvent.INITIAL_DATA_INSERTED,
			MongoPushTestEvent.SHUTDOWN_POC_DRIVER,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_DATA,
			MongoPushTestEvent.INITIAL_SYNC_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_VERIFY,
			MongoPushTestEvent.VERIFICATION_TASK_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH
			)),
	
	POC_DRIVER_MONGO_PUSH_DATA_SYNC_OPLOG(Arrays.asList(
			MongoPushTestEvent.EXECUTE_POC_DRIVER,
			MongoPushTestEvent.INITIAL_DATA_INSERTED,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_DATA,
			MongoPushTestEvent.INITIAL_SYNC_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_POC_DRIVER,
			MongoPushTestEvent.OPLOG_STREAMING_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH
			)),

	POC_DRIVER_MONGO_PUSH_DATA_ONLY_SYNC_ONE_DATABASE_VERIFY_REFETCH(Arrays.asList(
			MongoPushTestEvent.EXECUTE_POC_DRIVER,
			MongoPushTestEvent.INITIAL_DATA_INSERTED,
			MongoPushTestEvent.SHUTDOWN_POC_DRIVER,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_DATA_ONLY,
			MongoPushTestEvent.INITIAL_SYNC_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.POPULATE_DATA_ONE_DATABASE_NAME,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_VERIFY,
			MongoPushTestEvent.VERIFICATION_TASK_FAILED,
			MongoPushTestEvent.VERIFICATION_TASK_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_REFETCH,
			MongoPushTestEvent.REFETCH_TASK_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_VERIFY,
			MongoPushTestEvent.FINAL_VERIFICATION_TASK_COMPLETED
			)),
	
	POC_DRIVER_MONGO_PUSH_DATA_ONLY_SYNC_MULTIPLE_DATABASE_VERIFY_REFETCH(Arrays.asList(
			MongoPushTestEvent.EXECUTE_POC_DRIVER,
			MongoPushTestEvent.INITIAL_DATA_INSERTED,
			MongoPushTestEvent.SHUTDOWN_POC_DRIVER,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_DATA_ONLY,
			MongoPushTestEvent.INITIAL_SYNC_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.POPULATE_DATA_MULTIPLE_DATABASE,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_VERIFY,
			MongoPushTestEvent.VERIFICATION_TASK_FAILED,
			MongoPushTestEvent.VERIFICATION_TASK_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_REFETCH,
			MongoPushTestEvent.REFETCH_TASK_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_VERIFY,
			MongoPushTestEvent.FINAL_VERIFICATION_TASK_COMPLETED
			)),
	
	POC_DRIVER_MONGO_PUSH_DATA_SYNC_OPLOG_ONE_DATABASE_VERIFY_REFETCH(Arrays.asList(
			MongoPushTestEvent.EXECUTE_POC_DRIVER,
			MongoPushTestEvent.INITIAL_DATA_INSERTED,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_DATA,
			MongoPushTestEvent.INITIAL_SYNC_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_POC_DRIVER,
			MongoPushTestEvent.OPLOG_STREAMING_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.POPULATE_DATA_ONE_DATABASE_NAME,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_VERIFY,
			MongoPushTestEvent.VERIFICATION_TASK_FAILED,
			MongoPushTestEvent.VERIFICATION_TASK_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_REFETCH,
			MongoPushTestEvent.REFETCH_TASK_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_VERIFY,
			MongoPushTestEvent.FINAL_VERIFICATION_TASK_COMPLETED
			)),
	
	POC_DRIVER_MONGO_PUSH_DATA_SYNC_OPLOG_MULTIPLE_DATABASE_VERIFY_REFETCH(Arrays.asList(
			MongoPushTestEvent.EXECUTE_POC_DRIVER,
			MongoPushTestEvent.INITIAL_DATA_INSERTED,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_DATA,
			MongoPushTestEvent.INITIAL_SYNC_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_POC_DRIVER,
			MongoPushTestEvent.OPLOG_STREAMING_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.POPULATE_DATA_MULTIPLE_DATABASE,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_VERIFY,
			MongoPushTestEvent.VERIFICATION_TASK_FAILED,
			MongoPushTestEvent.VERIFICATION_TASK_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_REFETCH,
			MongoPushTestEvent.REFETCH_TASK_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_VERIFY,
			MongoPushTestEvent.FINAL_VERIFICATION_TASK_COMPLETED
			)),
	
	POC_DRIVER_MONGO_PUSH_DATA_SYNC_DATA_OPERATION_OPLOG_ONE_DATABASE_VERIFY_REFETCH(Arrays.asList(
			MongoPushTestEvent.EXECUTE_POC_DRIVER,
			MongoPushTestEvent.INITIAL_DATA_INSERTED,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_DATA,
			MongoPushTestEvent.INITIAL_SYNC_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_POC_DRIVER,
			MongoPushTestEvent.DATA_TYPE_OPERATIONS,
			MongoPushTestEvent.OPLOG_STREAMING_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.POPULATE_DATA_ONE_DATABASE_NAME,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_VERIFY,
			MongoPushTestEvent.VERIFICATION_TASK_FAILED,
			MongoPushTestEvent.VERIFICATION_TASK_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_REFETCH,
			MongoPushTestEvent.REFETCH_TASK_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_VERIFY,
			MongoPushTestEvent.FINAL_VERIFICATION_TASK_COMPLETED
			)),
	
	POC_DRIVER_MONGO_PUSH_DATA_SYNC_DATA_OPERATION_OPLOG_MULTIPLE_DATABASE_VERIFY_REFETCH(Arrays.asList(
			MongoPushTestEvent.EXECUTE_POC_DRIVER,
			MongoPushTestEvent.INITIAL_DATA_INSERTED,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_DATA,
			MongoPushTestEvent.INITIAL_SYNC_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_POC_DRIVER,
			MongoPushTestEvent.DATA_TYPE_OPERATIONS,
			MongoPushTestEvent.OPLOG_STREAMING_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.POPULATE_DATA_MULTIPLE_DATABASE,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_VERIFY,
			MongoPushTestEvent.VERIFICATION_TASK_FAILED,
			MongoPushTestEvent.VERIFICATION_TASK_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_REFETCH,
			MongoPushTestEvent.REFETCH_TASK_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_VERIFY,
			MongoPushTestEvent.FINAL_VERIFICATION_TASK_COMPLETED
			)),
	
	POC_DRIVER_MONGO_PUSH_DATA_SYNC_OPLOG_KILL_RESUME(Arrays.asList(
			MongoPushTestEvent.EXECUTE_POC_DRIVER,
			MongoPushTestEvent.INITIAL_DATA_INSERTED,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_DATA,
			MongoPushTestEvent.INITIAL_SYNC_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_POC_DRIVER,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.POPULATE_DATA_ONE_DATABASE_NAME,
			MongoPushTestEvent.RESUME_MONGO_PUSH,
			MongoPushTestEvent.POPULATE_DATA_ONE_DATABASE_NAME,
			MongoPushTestEvent.OPLOG_STREAMING_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_MONGO_PUSH_MODE_VERIFY,
			MongoPushTestEvent.FINAL_VERIFICATION_TASK_COMPLETED
			)),
	
	POC_DRIVER_OTHER_MIGRATION_TOOL_DATA_SYNC_OPLOG(Arrays.asList(
			MongoPushTestEvent.EXECUTE_POC_DRIVER,
			MongoPushTestEvent.INITIAL_DATA_INSERTED,
			MongoPushTestEvent.EXECUTE_OTHER_MIGRATION_TOOL,
			MongoPushTestEvent.INITIAL_SYNC_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_POC_DRIVER,
			MongoPushTestEvent.POPULATE_DATA_MULTIPLE_DATABASE,
			MongoPushTestEvent.OPLOG_STREAMING_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_OTHER_MIGRATION_TOOL_COMPARE,
			MongoPushTestEvent.FINAL_VERIFICATION_TASK_COMPLETED
			)),
	
	POC_DRIVER_OTHER_MIGRATION_TOOL_DATA_ONLY_SYNC_OPLOG(Arrays.asList(
			MongoPushTestEvent.EXECUTE_POC_DRIVER,
			MongoPushTestEvent.INITIAL_DATA_INSERTED,
			MongoPushTestEvent.SHUTDOWN_POC_DRIVER,
			MongoPushTestEvent.EXECUTE_OTHER_MIGRATION_TOOL,
			MongoPushTestEvent.INITIAL_SYNC_COMPLETED,
			MongoPushTestEvent.SHUTDOWN_MONGO_PUSH,
			MongoPushTestEvent.EXECUTE_OTHER_MIGRATION_TOOL_COMPARE,
			MongoPushTestEvent.FINAL_VERIFICATION_TASK_COMPLETED
			));
	
	private List<MongoPushTestEvent> mongoPushTestEvents;
	
	MongoPushTestSequence(List<MongoPushTestEvent> mongoPushTestEvents) {
		this.mongoPushTestEvents = mongoPushTestEvents;
	}

	public List<MongoPushTestEvent> getMongoPushTestEvents() {
		return mongoPushTestEvents;
	}
}
